version: "3.8"

services:
  server:
    build:
      dockerfile: ./infra/Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  postgres:
    image: "postgres:15-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=reed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    image: "redis:6.2-alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    ports:
      - 6379:6379

volumes:
  postgres_data: {}
